apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: python-app
  template:
    metadata:
      labels:
        name: python-app
    spec:
      containers:
        - name: python-app
          image: anas1243/python-redis-app
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "DEV"
            - name: HOST
              value: "localhost"
            - name: PORT
              value: "8000"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
